#!/bin/bash

sleep 5
xte 'keydown Control_L'
xte 'key r'
xte 'keyup Control_L'

sleep 5 

google-chrome "http://player.ngage-media.com/s/?u=546cc19e84b76822870741db&f=3&s=" &
#google-chrome "http://player.ngage-media.com/s/?u=546cc19e84b76822870741db&f=2&s=" &

sleep 6

./ngage_bot.sh
