#!/bin/bash

sleep 5
xte 'keydown Control_L'
xte 'key r'
xte 'keyup Control_L'

sleep 5 

google-chrome "http://player.ngage-media.com/s/?u=55f728ed3583702c350357c6&f=5&s=" &

sleep 6

./ngage_bot.sh
